name: Dev 

on: 
  push: 
    branches: ["dev"]

jobs: 
  build: 
    runs-on: 
      - 'self-hosted', 
      - 'Linux' 
      - 'X64'
      - 'dev-server'
    steps:
      - uses: actions/checkout@v3
      - name: docker check version
        run: docker -v